const con = (req, res) => {
  res.send([
    {
      link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWPtb4XCvvtehboRxNuinDcKH0SLY-rHwUWwkRq4uvnIWCYZjviRAU9Nm7YJejJKtk99M&usqp=CAU",
      productname: "Flower Port",
      prize: "Rs-250",
      desc: "best Selling Stylish pot",
    },
    {
      link: "https://rukminim1.flixcart.com/image/416/416/k1s6ljk0/mirror/m/g/r/beautiful-sunflower-wall-mirror-furnish-craft-original-imafh9wgeqabgrkg.jpeg?q=70",
      productname: "Lorem Mirror",
      prize: "Rs-350",
      desc: "Awesome mirror",
    },
    {
      link: "https://cdn.shopify.com/s/files/1/0005/4876/5743/products/New-Fashion-Men-s-Luxury-Stylish-Casual-Shirts-Fashion-Men-s-Casual-Printed-Floral-Long-Sleeve.jpg_0f55bbdd-0630-4e33-a9df-e45134dc247f_1200x1200.jpg",
      productname: "Raymonds-Shirt",
      prize: "Rs-550",
      desc: "Sliver Shirt",
    },
    {
      link: "https://cdn11.bigcommerce.com/s-pkla4xn3/images/stencil/1280x1280/products/30667/288101/New-Fashion-Man-Casual-Party-Shoes-Men-s-Lace-Up-Oxfords-Dress-Shoes-Mens-PU-Leather__44542.1580384730.jpg?c=2?imbypass=on",
      productname: "Fast-Track-shoes",
      prize: "Rs-420",
      desc: "Black shoes",
    },
    {
      link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRD1_Ldh4HBjrx9hB6olZvagIHtuQl3Eif6fgrJo3neTDh1MpJJ_RtueIFGem-_ZF9Gd3M&usqp=CAU",
      productname: "Blanket",
      prize: "Rs-299",
      desc: "Blankets",
    },
    {
      link: "https://5.imimg.com/data5/ANDROID/Default/2021/4/TV/AK/UJ/126482381/product-jpeg-500x500.jpg",
      productname: "Guci-prush",
      prize: "Rs-880",
      desc: "Prush",
    },
    {
      link: "https://cdn.opstatics.com/store/20170907/assets/images/events/2021/03/watches/en/common/1920/kv/kv-2.png",
      productname: "Fast-Track-watch",
      prize: "Rs-820",
      desc: "Watch",
    },
    {
      link: "https://m.media-amazon.com/images/I/51XrOYWEw9L._UL1500_.jpg",
      productname: "Fast-Track-glass",
      prize: "Rs-650",
      desc: "Black Glass",
    },
  ]);
};
const con1 = (req, res) => {
  res.send([
    {
      link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAYf_zCtjvHS8MghBVsH7iCGWc5tJd7p_O6J_O_Pgl6L3Vn0s&usqp=CAc",
      productname: "Sandel",
      prize: "Rs-650",
      desc: "best Selling Sandle",
    },
    {
      link: "https://static.toiimg.com/thumb/msid-86615130,width-1200,height-900,resizemode-4/.jpg",
      productname: "Ac 1ton",
      prize: "Rs-15250",
      desc: "Awesome Ac 1 ton",
    },
    {
      link: "http://cdn.home-designing.com/wp-content/uploads/2017/07/bedroom-table-lamps-600x600.jpg",
      productname: "Night Lamp",
      prize: "Rs-980",
      desc: "Stylish lamp",
    },
    {
      link: "https://staticimg.titan.co.in/Tanishq/Catalog/513218FPPAA00_1.jpg",
      productname: "Gold-Ring",
      prize: "Rs-10020",
      desc: "Tanishq Ring",
    },
    {
      link: "https://5.imimg.com/data5/YP/ML/MY-22208528/stylish-floor-carpet-500x500.jpg",
      productname: "Carpet",
      prize: "Rs-98",
      desc: "Carpet.",
    },
    {
      link: "https://m.media-amazon.com/images/I/51EW7sSIXVL._SL1100_.jpg",
      productname: "Loria Perfume",
      prize: "Rs-880",
      desc: "Perfume",
    },
    {
      link: "https://assets.ajio.com/medias/sys_master/root/20201008/aarQ/5f7e1733f997dd8c835b7845/-473Wx593H-4915691680-multi-MODEL.jpg",
      productname: "Cute-Cat",
      prize: "Rs-1500",
      desc: "Cutie cat",
    },
    {
      link: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkIs-B-jVDzoYBI_42Paw8wXbMEp4ikrmGiob5yZxlqpU4B_zqa2hzqzg0FyK_okDHB-0&usqp=CAU",
      productname: "Fast-Track-Bag",
      prize: "Rs-1000",
      desc: "League Bag",
    },
  ]);
};
const Sdata1 = (req, res) => {
  res.send([
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/kwcfngw0/jean/n/t/q/30-scs21jn-sstp-m-pln-bu-campus-sutra-original-imag9frv23sahgcz.jpeg?q=70",
      productname: "Spyker Jeans",
      desc: "Spyker offer",
      prize: "500",
    },
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/l3ahpjk0/shoe/t/i/2/5-380729-5-puma-white-white-gray-violet-original-imagefy4fxymxh2k.jpeg?q=70",
      productname: "shoes",
      desc: "Special offer",
      prize: "650",
    },
    {
      link: "https://assets.ajio.com/medias/sys_master/root/20201008/aarQ/5f7e1733f997dd8c835b7845/-473Wx593H-4915691680-multi-MODEL.jpg",
      productname: "Cute-Cat",
      prize: "Rs-1500",
      desc: "Cutie cat",
    },
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/kqttg280/necklace-chain/t/m/a/heartbeat-chain-brado-jewellery-original-imag4qwqsnnq92hh.jpeg?q=70",
      productname: "chain",
      desc: "gold chain",
      prize: "740",
    },
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/kixgtjk0-0/kids-track-pant/z/q/k/7-8-years-tblgy-wmboyjogger-crosline-tripr-original-imafym78az6vm8um.jpeg?q=70",
      productname: "Trouser",
      desc: "Trouser",
      prize: "700",
    },
    {
      link: "https://staticimg.titan.co.in/Tanishq/Catalog/513218FPPAA00_1.jpg",
      productname: "Gold-Ring",
      prize: "Rs-10020",
      desc: "Tanishq Ring",
    },
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/ju79hu80/backpack/m/t/b/valour-12148-laptop-backpack-wildcraft-original-imaffdnuguf4j4hh.jpeg?q=70",
      productname: "Bag",
      desc: "Stylish Bag",
      prize: "340",
    },
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/k1b1bbk0/jean/e/f/v/30-10187343-wrogn-original-imafkwrrexknhz7x.jpeg?q=70",
      productname: "blue Jeans",
      desc: "Loria jeans",
      prize: "654",
    },
    {
      sname: "Dark",
      link: "https://rukminim1.flixcart.com/image/150/150/l05lx8w0/shoe/f/u/i/7-1202a180-001-9-asics-black-ginger-peach-original-imagcydhzyem9bhp.jpeg?q=70",
      productname: "Black shoes",
      desc: "shoes..",
      prize: "412",
    },
  ]);
};

const mobpro = (req, res) => {
  res.send([
    {
      link: "https://m.media-amazon.com/images/I/91kAtEXPIeL._AC_UL320_.jpg",
      name: "Redmi Note 10T 5G (Mint Green, 4GB RAM, 64GB Storage) | Dual5G | 90HzAdaptive Refresh Rate | MediaTek Dimensity 700 7nm Processor | 22.5W",
      prize: "8999",
      fake_prize: "12500",
      freedom: "Great Freedom Sale",
      percent: "35%",
      bank_offer: "10% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 10 FREE Delivery by Amazon",
    },

    {
      link: "https://m.media-amazon.com/images/I/71AvQd3VzqL._AC_UL320_.jpg",
      name: "OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)",
      prize: "18999",
      fake_prize: "22500",
      freedom: "Great Freedom Sale",
      percent: "20%",
      bank_offer: "15% Off on ICICI Credit Cards",
      delivery_date: " Get it by Wednesday, August 15 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/81I6652dKDL._AC_UL320_.jpg",
      name: "Redmi Note 10T 5G (Mint Green, 4GB RAM, 64GB Storage) | Dual5G | 90Hz Adaptive Refresh Rate | MediaTek Dimensity 700 7nm Processor | 22.5W",
      prize: "10999",
      fake_prize: "12500",
      freedom: "Great Freedom Sale",
      percent: "19%",
      bank_offer: "4% Off on Bank Of Baroda Credit Cards",
      delivery_date: " Get it by Wednesday, August 8 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/812YsUxpyfL._AC_UL320_.jpg",
      name: "Samsung Galaxy M13 (Midnight Blue, 4GB, 64GB Storage) | 6000mAh Battery | Upto 8GB RAM with RAM Plus | 2000",
      prize: "11999",
      fake_prize: "14500",
      freedom: "Great Freedom Sale",
      percent: "12%",
      bank_offer: "18% Off on Bank Of Baroda Credit Cards",
      delivery_date: " Get it by Wednesday, August 12 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/61ahn9N38zL._AC_UL320_.jpg",
      name: "OnePlus Nord 2T 5G (Jade Fog, 8GB RAM, 128GB Storage) - Extra INR 3000 Exchange on Android Devices",
      prize: "28998",
      fake_prize: "32500",
      freedom: "Great Freedom Sale",
      percent: "6%",
      bank_offer: "12% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 18 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/919IyPIfczL._AC_UL320_.jpg",
      name: "Redmi 9 Activ (Metallic Purple, 4GB RAM, 64GB Storage)",
      prize: "8998",
      fake_prize: "12500",
      freedom: "Great Freedom Sale",
      percent: "13%",
      bank_offer: "9% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 18 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/810KHyQ4WcL._AC_UL320_.jpg",
      name: "Redmi 9A Sport (Coral Green, 2GB RAM, 32GB Storage) | 2GHz Octa-core Helio G25 Processor | 5000 mAh Battery",
      prize: "6999",
      fake_prize: "8500",
      freedom: "Great Freedom Sale",
      percent: "10%",
      bank_offer: "5% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 18 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/81vDZyJQ-4L._AC_UL320_.jpg",
      name: "Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM, 128GB Storage) with No Cost EMI & Additional Exchange Offers",
      prize: "39990",
      fake_prize: "45000",
      freedom: "Great Freedom Sale",
      percent: "14%",
      bank_offer: "8% Off on AXIS_Bank Credit Cards",
      delivery_date: " Get it by Wednesday, August 8 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/71Q3iSQAwAS._AC_UL320_.jpg",
      name: "Samsung Galaxy M32 (Black, 6GB RAM, 128GB | FHD+ sAMOLED 90Hz Display | 6000mAh Battery | 64MP Quad Camera",
      prize: "13999",
      fake_prize: "16500",
      freedom: "Great Freedom Sale",
      percent: "8%",
      bank_offer: "8% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 18 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/81gRC3KTeaL._AC_UL320_.jpg",
      name: "realme narzo 50 (Speed Blue, 6GB RAM+128GB Storage) Helio G96 Processor | 50MP AI Triple Camera | 120Hz Ultra Smooth",
      prize: "14499",
      fake_prize: "16499",
      freedom: "Great Freedom Sale",
      percent: "6%",
      bank_offer: "10% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 18 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/81Ke5qtC6oL._AC_UL320_.jpg",
      name: "realme narzo 50A (Oxygen Blue , 4GB RAM + 64 GB Storage) Helio G85 Processor | 6000 mAh Battery",
      prize: "12399",
      fake_prize: "14499",
      freedom: "Great Freedom Sale",
      percent: "8%",
      bank_offer: "12% Off on BOB Credit Cards",
      delivery_date: " Get it by Wednesday, August 14 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/91J1pz6vBcL._AC_UL320_.jpg",
      name: "Tecno Spark 9 (Sky Mirror, 6GB RAM, 128GB Storage)| Upto 11GB Expandable RAM | 90Hz Refresh Rate | 6.6 HD+Display |",
      prize: "15999",
      fake_prize: "18499",
      freedom: "Great Freedom Sale",
      percent: "10%",
      bank_offer: "12% Off on BOB Credit Cards",
      delivery_date: " Get it by Wednesday, August 14 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/71lx0qz7rFL._AC_UL320_.jpg",
      name: "Redmi Note 11 Pro + 5G (Stealth Black, 6GB RAM, 128GB Storage) | 67W Turbo Charge | 120Hz Super AMOLED Display |",
      prize: "18999",
      fake_prize: "20499",
      freedom: "Great Freedom Sale",
      percent: "5%",
      bank_offer: "15% Off on BOB Credit Cards",
      delivery_date: " Get it by Wednesday, August 14 FREE Delivery by Amazon",
    },

    {
      link: "https://m.media-amazon.com/images/I/81S-XYJlzTL._AC_UL320_.jpg",
      name: "Redmi Note 10 Pro (Dark Night, 6GB RAM, 128GB Storage) -120hz Super Amoled Display|64MPwith 5mp Super",
      prize: "15999",
      fake_prize: "18499",
      freedom: "Great Freedom Sale",
      percent: "9%",
      bank_offer: "10% Off on BOB Credit Cards",
      delivery_date: " Get it by Wednesday, August 12 FREE Delivery by Amazon",
    },

    {
      link: "https://m.media-amazon.com/images/I/61cU9G3nwVL._AC_UL320_.jpg",
      name: "iQOO Z6 5G (Chromatic Blue, 6GB RAM, 128GB Storage) | Snapdragon 695-6nm Processor | 120Hz FHD+ Display | 5000mAh",
      prize: "16999",
      fake_prize: "20499",
      freedom: "Great Freedom Sale",
      percent: "3%",
      bank_offer: "8% Off on SBI Credit Cards",
      delivery_date: " Get it by Wednesday, August 10 FREE Delivery by Amazon",
    },
    {
      link: "https://m.media-amazon.com/images/I/81kFQpwRonL._AC_UL320_.jpg",
      name: "Tecno Spark 8C Turquoise Cyan (3GB+64GB) | Upto 6GB RAM |90Hz Refresh Rate |6.6 HD+ Display | 5000mAh |13MP Dual",
      prize: "8799",
      fake_prize: "10099",
      freedom: "Great Freedom Sale",
      percent: "8%",
      bank_offer: "7% Off on ICICI Credit Cards",
      delivery_date: " Get it by Wednesday, August 10 FREE Delivery by Amazon",
    },
  ]);
};
export { con, con1, Sdata1, mobpro };
